### ISSUE TITLE
French applet of contextual-wiktionary is broken or incomplete.

### ISSUE THREAD

**Issue by ineuw** [AesaraB/contextual-wiktionary#67] opened 2024-10-06 19:56 UTC
I am trying to use it in French FF 131.0, and the interface is incomplete when compared to the same extension English Wiktionary.

**Comment by AesaraB** [comment] 2024-10-08 01:47
Duplicate of #40

**Closed as not planned by AesaraB** 2024-10-08 01:47 UTC

**Comment by ineuw** [comment] 2024-10-08 02:53
Does this mean that there is no intention to correct it? I am OK with it. This is not the only fish in the ocean.

**Comment by AesaraB** [comment] 2024-10-08 02:56
Due to the disparate formatting of Wiktionary, the API only exists for English. It should be possible to format other languages manually using the MediaWiki API, but that's a bit of an undertaking.

When I get to the next spurt of fixes, I'll look into this.

**Comment by ineuw** [comment] 2024-10-08 13:29
Thanks for explaining.
